(define (make-point x y) (cons x y))
(define (x-point point) (car point))
(define (y-point point) (cdr point))

(define (make-segment start end) (cons start end))
(define (start-segment segment) (car segment))
(define (end-segment segment) (cdr segment))
(define (segment-length segment)
  (cond ((= (x-point (start-segment segment))
            (x-point (end-segment segment)))
         (abs (- (y-point (start-segment segment))
                 (y-point (end-segment segment)))))
        ((= (y-point (start-segment segment))
            (y-point (end-segment segment)))
         (abs (- (x-point (start-segment segment))
                 (x-point (end-segment segment)))))
        (else (error "not a straight line"))))
         
(define (plane-rectangle a b c d)
  (define (bases upper lower) (cons upper lower))
  (define (heights left right) (cons left right))
  (cons (bases (make-segment a b)
               (make-segment c d))
        (heights (make-segment a c)
                 (make-segment b d))))

(define (lower-base rectangle)
  (car (car rectangle)))
(define (upper-base rectangle)
  (cdr (car rectangle)))
(define (left-height rectangle)
  (car (cdr rectangle)))
(define (right-height rectangle)
  (cdr (cdr rectangle)))

(define (plane-rectangle-perimeter rectangle)
  (+ (segment-length (upper-base rectangle))
     (segment-length (lower-base rectangle))
     (segment-length (left-height rectangle))
     (segment-length (right-height rectangle))))

(define (plane-rectangle-area rect)
  (* (segment-length (lower-base rect))
     (segment-length (right-height rect))))

(define (geo-rectangle base height) (cons base height))
(define (base-geo-rect rect) (car rect))
(define (height-geo-rect rect) (cdr rect))

(define (perimeter-geo-rect rect)
  (+ (* 2 (base-geo-rect rect))
     (* 2 (height-geo-rect rect))))

(define (area-geo-rect rect)
  (* (base-geo-rect rect) (height-geo-rect rect)))

(define (perimeter-rect rect)
  (perimeter-geo-rect rect))

(define (area-rect rect)
  (area-geo-rect rect))

(define rect (plane-rectangle (make-point 1 1)
                              (make-point 11 1)
                              (make-point 1 11)
                              (make-point 11 11)))
